name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        distribution: 'zulu'
        java-version: 8
    - name: run unitTest
      run: ./gradlew testDebugUnitTest assembleDebug
